apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev
  region: us-east-2

nodeGroups:
  - name: v4
    minSize: 2
    maxSize: 3
    volumeSize: 5
    privateNetworking: true
    instancesDistribution:
      maxPrice: 0.007
      instanceTypes: ["t3.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotInstancePools: 3
    iam:
      instanceProfileARN: "arn:aws:iam::006396608450:instance-profile/eksctl-dev-nodegroup-a1-NodeInstanceProfile-XNYE00ZZU2DY"
      instanceRoleARN: "arn:aws:iam::006396608450:role/eksctl-dev-nodegroup-a1-NodeInstanceRole-1I4LVNJH23P8O"
