apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev
  region: us-east-2

nodeGroups:
  - name: a1
    minSize: 6
    maxSize: 10
    volumeSize: 5
    privateNetworking: true
    instancesDistribution:
      maxPrice: 0.004
      instanceTypes: ["t3.nano", "t3.micro"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotInstancePools: 2
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/aws-k8s-dev.pub
    iam:
      withAddonPolicies:
        autoScaler: true
