apiVersion: v1
kind: Service
metadata:
  name: caworkflow
  labels:
    app: caworkflow
spec:
  type: NodePort
  selector:
    app: caworkflow
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
