apiVersion: v1
kind: Service
metadata:
  name: connectorengine
  labels:
    app: conncectorengine
spec:
  type: NodePort
  selector:
    app: conncectorengine
  ports:
    - name: http
      protocol: TCP
      port: 9092
      targetPort: 9092
